meta_title: "Le raid de l'hermine"
meta_description: "Le raid de l'hermine est une équipe de l'Europ'Raid"
meta_image: "http://img15.hostingpics.net/pics/645154hermine.png" # Une image dans votre dossier app/assets/images/
